### ISSUE TITLE
Build error on CDK 2.1 OSE 3.2

### ISSUE THREAD

**Issue by alberttwong** [codecentric/springboot-sample-app#1]
Followed the instructions and when you do the build, it doesn't like it. 

I0802 22:19:21.953857       1 docker.go:351] Image "codecentric/springboot-maven3-centos@sha256:ce5df150264029c727ae62c89c185fba6751f8e1312ca7e439dd2fd6e14b6e00" not available locally, pulling ...
I0802 22:19:25.630839       1 docker.go:351] Image "codecentric/springboot-maven3-centos@sha256:ce5df150264029c727ae62c89c185fba6751f8e1312ca7e439dd2fd6e14b6e00" not available locally, pulling ...
F0802 22:19:28.533289 1 builder.go:204] Error: build error: unable to get codecentric/springboot-maven3-centos@sha256:ce5df150264029c727ae62c89c185fba6751f8e1312ca7e439dd2fd6e14b6e00

**Comment by alberttwong** [comment]
You have to do a local build of everything.   Start with s2i build from https://github.com/codecentric/springboot-maven3-centos

**Comment by alberttwong** [comment]
So the problem is that dockerhub updated the registry schema.   Answer is https://access.redhat.com/solutions/2391351

**Comment by britter** [comment]
@alberttwong thank you for coming back with the solution!
